### ISSUE TITLE
Unmount

### ISSUE THREAD

**Issue by Djaler** [teejee2008/timeshift#10]
Looks like you forgot to unmount /mnt/timeshift/backup after app close in btrfs mode.

**Comment by teejee2008** [comment]
It's intentional. There's no harm in leaving it mounted for the next scheduled backup.

**Comment by Djaler** [comment]
It works wrong with btrfs. Nested snapshots created

**Comment by emanuc** [comment]
umount snapshot is an important feature, for example it saves you if you accidentally type a command that damages the system: "sudo rm -rf / *".
I made a video on this feature that had timeshift-btrfs, ie the ability to restore the system after typing the command that damages the whole system (sudo rm -rf / *): https://www.youtube.com/watch?v=VdmDJ3cBmZM&t=250s
With timeshift I tried, it also eliminates the snapshot, so it is no longer possible to recover the system.

**Comment by Stibila** [comment]
Can we reopen this as feature request? I too think that leaving mounted snapshots is bad idea.

**Comment by Djaler** [comment]
IMHO, this can be related to #141

**Comment by emanuc** [comment]
Could you put a flag if setting a snapshot in RO?
So another advantage is that you could use "btrfs send" to export it to another disk.
`btrfs property set -ts /path/to/snapshot ro true`

[https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-property#btrfs-property.288.29_manual_page](url)

**Comment by Golddouble** [comment]
I also would like to have this in rsync mode.
I guess, this woulöd also solve this unexpected behaviour:
https://github.com/teejee2008/timeshift/issues/675

**Comment by erikjms** [comment]
I am also interested in a better way to manage timeshift volumes. I backup to a micro SD card in my laptop, and often I want to use the single micro SD port for something else. Using the command line to unmount the timeshift volume without knowing whether timeshift is currently writing to that volume seems unwise--although, in the grand scheme of things, perhaps not catastrophically so. But it might result in a corrupted backup, and depending on how many backups one keeps on hand, that could be quite annoying.

It would be nice either: to have a tool to unmount the volume after checking that timeshift is not currently writing/reading it; or for timeshift simply to mount/unmount the volume as needed. Myself, I'm not good enough a bash wrangler to know how best to safely unmount the volume with a custom shell script. Otherwise that is precisely what I would do.
