### ISSUE TITLE
Add logrotate configuration

### ISSUE THREAD

**Issue by zunpiau** [teejee2008/timeshift#106]
There are a lot of log files in the `/var/log/timeshift/`. It may be a good idea to support log rotate.
This is my simple configuration: 
````
/var/log/timeshift/*.log {
	daily
	missingok
	rotate 7
	compress
	delaycompress
	notifempty
	nocreate
}
````

**Comment by teejee2008** [comment]
500 log files are kept at maximum, so that log files will be available for last 20 days (24 files x 20 days). Log files are roughly 10 KB in size, so 500 files will take up about 5 MB of space.
Older files are deleted automatically, there's no need for logrotate.

Do you have more than 500 files in /var/log/timeshift/ ?

**Comment by zunpiau** [comment]
Thanks for the answer. 
No, there are not so much files.
