### ISSUE TITLE
There is no text under either the 'Warning' or the 'Disclaimer' heading

### ISSUE THREAD

**Issue by ghost** [teejee2008/timeshift#260]
Mint 19, both on live CD and on the installed system.

**Comment by clefebvre** [comment]
I you click next before the text appears, the wizard continues to the next page and the restoration fails. If you wait for the text to appear and then click next, you're presented with the fullscreen grey restoration screen and the restoration starts.

**Comment by LinuxOnTheDesktop** [comment]
Still present on TimeShift 19.01: the text took some 10 seconds to show up on my very fast laptop. This delay - or, worse, longer ones - will scare people, I think. At the least some sort of: 'Loading ..' text is needed.

**Comment by Fabio-HW** [comment]
Still, apparently, unresolved (Linux Mint 19.3). Actually I failed to restore my system once, seemingly due to this very issue.

**Comment by andrewdbate** [comment]
This issue appears related to https://github.com/teejee2008/timeshift/issues/673. That issue reported blank 'Warning' and 'Disclaimer' text followed by a failed restore. I expect that the two issues are separate.

**Comment by andrewdbate** [comment]
When this issue is fixed it would be nice to resolve https://github.com/teejee2008/timeshift/issues/481 at the same time (mistake in 'Disclaimer' text).

**Comment by andrewdbate** [comment]
Here is a video of this bug. I am running Timeshift v21.09.1 on elementary OS 6.1. In this case the 'Warning' and 'Disclaimer' text took 23 seconds to appear.

https://user-images.githubusercontent.com/2998569/156565600-4a46e855-4f0e-42b2-904c-66701e3a5df5.mp4

The 'Disclaimer' text should be instant because it is the same each time.

**Comment by andrewdbate** [comment]
It would be good if there was a way to sponsor bug fixes on this project.

**Comment by LinuxOnTheDesktop** [comment]
> It would be good if there was a way to sponsor bug fixes on this project.

That might be a way of getting bugs fixed. I feel though that I should not have to pay for Timeshift bug fixes. For, I sponsor Mint already and Timeshift is part of Mint.

Mint should be unsatisfied that its backup tool has the problems that it does. We have here an instance of the sort of moderate-sized defect that plagues Mint and stops Mint from being a really good Linux distribution.

**Comment by teejee2008** [comment]
@LinuxOnTheDesktop Linux Mint and Timeshift are two separate projects. If you are sponsoring Linux Mint you should ask Linux Mint developers to help with development since they rely on Timeshift for backups.

I had a discussion with Clement on this topic and he was interested in taking over the maintainance. But they are not sure if they want to keep Timeshift as it is, or create a Mint-specific fork. Forking or maintaining Timeshift will be a significant burden due to the large number of users who use Linux Mint.

**Comment by LinuxOnTheDesktop** [comment]
@teejee2008 : thanks. I will seek an opportunity to remind the Mint team of the matter that you mention.

Now, returning to the bug in hand . .
