### ISSUE TITLE
Plain text backup of encrypted home

### ISSUE THREAD

**Issue by hozza** [teejee2008/timeshift#270]
Hi!

Timeshift looks like the perfect balance of simple rsync hard link backups with easy configuration!

However, I'd like to backup my encrypted home as plain non-encrypted files... (the destination HDD is encrypted at the partition level) - I know I'd need to be logged in when backups run for the home dir to be decrypted (no boot backups)... 

But it looks like this feature was remove some versions ago by default, is it possible to configure Timeshift to do this somehow?

**Comment by teejee2008** [comment]
This feature was removed because it makes the decrypted contents of home directory available outside the home directory (in snapshot folder). There's no point of encrypting your home directory if the decrypted contents are stored in another location. It also causes problems with restore. Use LUKS-encrypted partitions if you want to use encryption.
