### ISSUE TITLE
Current encrypted home backup handling may lead to unexpected behavior

### ISSUE THREAD

**Issue by kenogo** [teejee2008/timeshift#398]
v17.10 introduced backing up the files in `/home/.ecryptfs/*/***` rather than backing up the decrypted files. However, ecryptfs does [not support modifying the Private directory while mounted](https://bugs.launchpad.net/ecryptfs/+bug/689030). This means that restoring a backup could lead to unexpected behavior (I actually haven't tried it yet, though, since I still need to set up a good test environment for that).

I understand the reasoning behind introducing backups in this way. I'm not even saying this should be removed. However, I currently found no way to backup the decrypted files, which is perfectly reasonable to do since my backup drive is encrypted with dm-crypt. Ideally, I think it would be best if you could select between the two options. However, I would also be fine with a workaround for now (maybe tricking timeshift into not realizing there's a `.ecryptfs` directory).

**Comment by kenogo** [comment]
Forgot to say: Adding a filter does not work, since the filters are listed right after each other like:

```
/home/user/**
+ /home/user/**
```

which apparently leads to `/home/user/**` not being backed up

**Comment by teejee2008** [comment]
This is by design. It is not possible to include decrypted home directory content in the snapshot. Restoring the decrypted contents when the user is not logged in will fill /home/user with content that is accessible to everyone. When the user logs in, the contents of /home/user will be hidden by the contents of the encrypted directory which gets mounted on top of existing data in /home/user (which is supposed to be empty). User will continue using his account without realising that his home directory data is accessible to everyone **when he is not logged in**.

If you are concerned about restoring the encrypted data while the folder is mounted,
you can do the restore when the encrypted home is not mounted. Log out of user accounts having an encrypted home, log in to a guest user account (with a normal home directory) and restore the snapshot.

**Comment by kenogo** [comment]
Okay, thank you for clarifying! I also just read that TimeShift is not really intended for home backups in the first place, so I'll just use manual rsync for that.
