### ISSUE TITLE
[Suggestion] Feature to use Timeshift from Grub Menu to restore to prior good working state of Linux distro.

### ISSUE THREAD

**Issue by setsunati** [teejee2008/timeshift#414]
Visual Representation: https://i.imgur.com/xlG4oRX.png

This feature will be very handy when you can't boot to desktop and when you don't have live Linux distro USB on you. Also this way i wont have to use command line to use Timeshift snapshots. I simply select Timeshift snapshot in grub menu to restore to prior good working state.

**Comment by MostHated** [comment]
I definitely second this. I could have used it earlier when my Windows 10 recovery somehow took out my linux install on a completely separate drive on it's own...

**Comment by Powellga** [comment]
YES - Excellent Idea - Mine is the third request for such a feature.

Thanks.
Gregg
AZ

**Comment by Buri** [comment]
I would also love to see this

**Comment by clefebvre** [comment]
@setsunati, that's a really cool idea, is that just a mockup, or you have ideas on how to implement it?

**Comment by Powellga** [comment]
Have no ideas on how to implement it of course.

Regards.
Gregg

-------- Original Message --------

**Comment by Buri** [comment]
Maybe take a look at OpenSUSE's Snapper? It offers similar functionality (altho different implementation) using patched grub afaik

**Comment by Powellga** [comment]
I much prefer the PCLinuxOS distro. So I'm stuck with what's on their respository. I've installed from outside the repository on a few occasions and inevitably it breaks something.

Also with timeshift, I imagine integrating it with grub or grub2 so that the GUI is modified so that one may select a restore point prior to boot.... I think that would be a very tricky thing to develop. But, is it possible? It would be an awesome next step for your application.

Anyway, I do very much appreciate timeshift, enough to have contributed to it. Thank you for your time and effort developing one of the most useful applications available in Linux.

Gregg
AZ

-------- Original Message --------

**Comment by enchance** [comment]
Having Timeshift integrated into GRUB is actually very beneficial to your users since it will reboot anyway. This would increase Timeshift in terms of **speed**, **efficiency** in replacing old files, and OS **stability** as well. At best, I wouldn't consider this a feature but rather a major upgrade for its upcoming releases.

I'd love to see this in the near future.

**Comment by lisandrocarmona** [comment]
This is not only desirable, but also possible. https://garudalinux.org has already implemented that.

**Comment by teejee2008** [comment]
This is something to be implemented in GRUB or in distribution-specific scripts. Take a look at [grub-btrfs](https://github.com/Antynea/grub-btrfs) and similar projects.
