### ISSUE TITLE
Cron Jobs not working Arch Linux

### ISSUE THREAD

**Issue by callmekory** [teejee2008/timeshift#42]

**Comment by RPINerd** [comment]
Well just to expand a bit, I too am not seeing the cron jobs executing correctly. They are present within the /etc/cron.d/ directory but not in the .hourly, .daily, etc. In the /etc/cron.d/timeshift-hourly is the following:

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 * * * * root timeshift --check --scripted


Looking at other unrelated cron issues, one common theme seems to be not having permissions to access libraries required? I'm not knowledgeable enough to expand on this, but whenever I run timeshift manually I have to use the root password, so maybe there is a permissions issue between cron and timeshift?

Otherwise I love the tool, just looking forward to getting it fully automatic!

**Comment by navarroaxel** [comment]
How did you install `timeshift`? With aurman works fine.
I have the same `/etc/cron.d/timeshift-hourly` config and it's working good with the cronie.service. Remember check cronie.service enabled to autostart when the OS boot.

Which is the log from `systemctl status cronie.service`?

**Comment by RPINerd** [comment]
So I installed with aurman on one system and yay on the other. Both exhibited the same issues but doing `systemctl enable cronie.service` has seemed to sort out the issue entirely. Perhaps there is a way to enable cronie in systems that default to it being disables? Either way thank you for your help! Awesome program!

**Comment by gmish27** [comment]
I have my cronie service enabled but Timeshift hasn't created any scheduled monthly snapshots.

**Comment by navarroaxel** [comment]
@gmish27 I'm not an expert using `cronie`, I just installed `timeshift` using `aurman` and it's works.

I have a `/etc/cron.d/0hourly` file that runs hourly, `timeshit` is design to run hourly and check if they need to make a backup, so your monthly backup still execute `timeshift` every hour to check it. And the `cronie` configuration is part of the `timeshift` compilation not in the AUR package.

**Comment by navarroaxel** [comment]
@gmish27 Can you run `sudo timeshift --list` or you got an error? sometimes cleaning orphan packages breaks `timeshift` that's an issue with the AUR package. You need to re-install to fix it.

**Comment by gmish27** [comment]
It works for me now. Apparently, no crontab file was created by the application on its own. I created an entry one and it's creating backup on schedule.

So, two things the application doesn't do on its own:
1. Enable cronie service, if not enabled explicitly by the user.
2. Touch a crontab file to work with.

**Comment by shinanqu** [comment]
I have Manjaro, installed Timeshift with Pamac.

When I run "systemctl status cronie.service" I get this output:

`[mark@manjaro-2019-11 ~]$ systemctl status cronie.service
● cronie.service - Periodic Command Scheduler
   Loaded: loaded (/usr/lib/systemd/system/cronie.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2019-11-09 23:10:49 +07; 59min ago
 Main PID: 560 (crond)
    Tasks: 1 (limit: 4915)
   Memory: 1.9M
   CGroup: /system.slice/cronie.service
           └─560 /usr/bin/crond -n

Nov 09 23:10:49 manjaro-2019-11 crond[560]: (CRON) INFO (Syslog will be used instead of sendmail.)
Nov 09 23:10:49 manjaro-2019-11 crond[560]: (CRON) INFO (RANDOM_DELAY will be scaled with factor 21% if used.)
Nov 09 23:10:49 manjaro-2019-11 crond[560]: (CRON) INFO (running with inotify support)
Nov 10 00:00:01 manjaro-2019-11 crond[560]: (root) CAN'T OPEN (/etc/crontab): No such file or directory
Nov 10 00:01:01 manjaro-2019-11 crond[560]: (root) CAN'T OPEN (/etc/crontab): No such file or directory
Nov 10 00:01:01 manjaro-2019-11 CROND[8385]: (root) CMD (run-parts /etc/cron.hourly)
Nov 10 00:01:01 manjaro-2019-11 anacron[8390]: Anacron started on 2019-11-10
Nov 10 00:01:01 manjaro-2019-11 anacron[8390]: Normal exit (0 jobs run)
Nov 10 00:08:01 manjaro-2019-11 crond[560]: (root) CAN'T OPEN (/etc/crontab): No such file or directory
Nov 10 00:08:01 manjaro-2019-11 crond[560]: (root) BAD FILE MODE (/etc/cron.d/timeshift-hourly)
`

What does BAD FILE MODE mean? The file was created automatically by Timeshift, I didn't touch it. At least it exists. And I think backups are indeed created, but irregularly. I want daily backups, and sometimes 2 days pass, the computer is on all day, but no backup is created.

**Comment by shinanqu** [comment]
Ok, everything is working. Perhaps I just misunderstood the journal before, somehow I thought the error message are real time and did not see the time. Anyway, I am not sure if the mode was an issue in the first place. I guess 744 or 644 is fine, probably it was all fine from the beginning. The main issue that I had, and perhaps some others, is:
`CMDOUT (Another instance of this application is running (PID=11472))`
As long as the application is open, cron (or the terminal) can't create a backup. I had the window eagerly open, in hope that a backup will suddenly pop up. But instead I just had to close Timeshift and let cron do the work in the background.
