### ISSUE TITLE
schedule Timeshift dont work

### ISSUE THREAD

**Issue by AleDoctors** [teejee2008/timeshift#467]
Hi, I recently started using timeshift and I find that in previews and some other arch files, I don't execute the scheduled tasks. I don't know what I'm missing. Manually works are problems.
Anyone have any idea what I am doing wrong?
thanks for your help

**Comment by Xwang1976** [comment]
I have the same issue.
Cronie is running and if I manually execute 
sudo timeshift --check --scripted
it executes the snapshots that it should have done automatically.

**Comment by Xwang1976** [comment]
Now at 17:57 this is the situation of the snapshot hourly folder (I have set to keep 24 hourly backup, 5 boot backup, 5 daily backup and 2 monthly backup):
drwxr-xr-x 2 root root 4096 14 ott 17.00 .
drwxr-xr-x 9 root root 4096 14 ott 17.00 ..
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-13_18-32-37 -> ../snapshots/2019-10-13_18-32-37
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-13_20-05-33 -> ../snapshots/2019-10-13_20-05-33
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-13_22-00-01 -> ../snapshots/2019-10-13_22-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-13_23-00-01 -> ../snapshots/2019-10-13_23-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_00-00-01 -> ../snapshots/2019-10-14_00-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_01-00-01 -> ../snapshots/2019-10-14_01-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_02-00-01 -> ../snapshots/2019-10-14_02-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_03-00-01 -> ../snapshots/2019-10-14_03-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_04-00-01 -> ../snapshots/2019-10-14_04-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_05-00-02 -> ../snapshots/2019-10-14_05-00-02
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_07-00-01 -> ../snapshots/2019-10-14_07-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_08-00-01 -> ../snapshots/2019-10-14_08-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_09-00-01 -> ../snapshots/2019-10-14_09-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_10-00-01 -> ../snapshots/2019-10-14_10-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_11-00-01 -> ../snapshots/2019-10-14_11-00-01
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_12-00-03 -> ../snapshots/2019-10-14_12-00-03
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_13-44-50 -> ../snapshots/2019-10-14_13-44-50
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_14-22-56 -> ../snapshots/2019-10-14_14-22-56
lrwxrwxrwx 1 root root   32 14 ott 17.00 2019-10-14_16-00-02 -> ../snapshots/2019-10-14_16-00-02

It seems as if it skips the hourly backup if the time of the previous backup is after the first second of the previous backup.
In fact it has not made the backup after 2019-10-14_05-00-02, after 2019-10-14_12-00-03 and after 2019-10-14_16-00-02 only because the system has taken one or two second more to execute.
Is it something configurable in the program?
