### ISSUE TITLE
[Feature request] Add some sort of remote location to save snapshots

### ISSUE THREAD

**Issue by q2dg** [teejee2008/timeshift#52]
Nowadays snapshots can only be saved on local partitions/disks. 
Would it be a crazy idea if there was some other options like NFS/Samba/SSHFS/WebDAV/whatever-mounted folders (like Deja-Dup offers, for instance)?
Thanks!

**Comment by teejee2008** [comment]
Timeshift snapshots use hard-links which is not supported by cloud storage file systems. Hence there is no way to move the snapshots to cloud storage. You can copy the snapshots folders manually, but the hard-links will break and snapshots will take up a huge amount of space. There's no workaround for this and therefore it is not supported.

**Comment by mauromol** [comment]
But Samba with Unix extensions and NFS do support hard linking, so why not supporting this kind of network file systems? Not to say about SSH.

I'm using a Samba share with BackInTime (which uses hardlinks & rsync) with no problems. It would be very useful to have remote location support when using a laptop.

**Comment by Kudalufi** [comment]
Is this possible now by making /timeshift an nfs mount?

Is there any movement on this?  Remotely storing a backup would be ideal.

**Comment by Schroedingers-Cat** [comment]
@teejee2008 it is my understanding that SSHFS has great support for hard-links. So that should not hold you back, should it?  

I tried to mount an ext4 partition via SSHFS into /timeshift in order to trick timeshift into remote backup. But when starting the timeshift job, I get a bizzare error message, that timeshift needs roughly 744GB to backup the 30GB system partition. It is my guess that timeshift also looks into the /timeshift directory and takes all the files in there into account when calculating the necessary free disk space. I also tried to list the /timeshift folder in the /etc/timeshift.json exlusion list, but that didn't help. Once I select a local target drive, timeshift successfully creates a 10GB snapshot (so the 744GB estimation is really far off). This seems like a bug with the exclusion list being ignored during the calculation of the required free disk space. If it isn't, is there a way to ignore that error?

**Comment by teejee2008** [comment]
The estimation is broken because you are trying to force the program to do something that it is not meant to do. Even if you manage to somehow create a backup on a remote drive, you will not be able to restore it without doing a lot of additional work.

As mentioned previously, there are no plans to add this feature as there is nobody to work on it. If someone can take up this work please go ahead. I won't be merging any PRs for this though, because of the complexity it will introduce.

**Comment by Schroedingers-Cat** [comment]
From this conversation I cannot see any mentioning that "there is nobody to work on it" - sorry if that has been brought up in another Issue.  

Right now, this thread only names "hard-links" as the problem preventing network backup. I wonder what else?

**Comment by Schroedingers-Cat** [comment]
This program uses rsync at its core ("Select snapshot type" -> rsync). Rsync can be used to directly store the snapshot on a [remote storage via sftp](https://linux.die.net/man/1/rsync) with a command like `rsync [OPTION...] [USER@]HOST::SRC... [DEST]`. @teejee2008 What exactly is this program doing that it cannot use this already built-in feature of rsync?

**Comment by teejee2008** [comment]
It's not impossible. It's just a lot of work. Please go ahead if you wish to add this feature.

**Comment by bruceleerabbit** [comment]
To be clear, this is not just a convenience feature that is nice to have -- offsite backups are **essential** for security.  A backup tool that forces a local drive destination is not ready for prime-time.  It's a big vulnerability.  When there is a local disaster, you want your data to be somewhere else.  I'm not sure what the core developers are working on that's more important than this.

I'm a bit frustrated because normally I would just walk away from Timeshift and use Duplicity.  But linux Mint has been designed so that admins are *forced* to use Timeshift before doing a dist-upgrade.

**Comment by Schroedingers-Cat** [comment]
@bruceleerabbit I tried the same trick and this is what happened: https://github.com/teejee2008/timeshift/issues/52#issuecomment-449354311

**Comment by zer0lean** [comment]
Did someone find a solution for this?

**Comment by igelkotten** [comment]
Disclaimer: I have not yet tried timeshift, so these are assumptions but I think my theory holds(I would love to hear if it doesn't)

Couldn't you just mount a sshfs/nfs/smb share and create a single file that you emulate as a drive (https://superuser.com/questions/518554/how-do-you-create-and-partition-a-raw-disk-image) you then simply point timeshift to run backups on the raw diskimage 'dev' location. This would then emulate as a drive that you might be able to point to using timeshift?

Looking at the 'gui' https://itsfoss.com/backup-restore-linux-timeshift/ timeshift might be looking for 'pure physical disks' based on drivers or other means to differentiate emualte disks so you might need to point to it using the configuration files or some cli commands.

Then in theory that should work? **But** I have some concerns having it 'remote' as if you f-up your network drivers or something you will ofcourse not be able to simply locally 'timeshift' back. Maybe the raw file can be exported to a drive or some other ways of getting timeshift to create a a 'point in time' that you could export to another file that you then import?

Like: timeshift get-exact-files-at-date xx-yy-zz --export-to-dummy-file drivestate.raw
and then simply dd if=drivestate.raw of=/dev/sd{X}

**However** for most happy penguincampers I think another backup solution is preferred for 'media' and then use timeshift as it's intended purposes. Perhaps try to separate all your media to other drives or(I assume timeshift support lvms or even exclusions of folders) so you back these up using some 'copy-on-write' and validate these are running and then you just timeshift the drive/lv that contains boot and root applications.

**Comment by JeRoNZ** [comment]
It is possible to set up an rsync service on another linux box, and to use hard links for unchanged files. I've been doing this for several years with a cloud storage service as the backup device. The options to make this work are --link-dest=DIR --inplace. e.g.
rsync -vrlptDh --modify-window=1 --inplace --link-dest=YESTERDAY DIR rsync://user@host:/path/to/backup/TODAY/

where YESTERDAY is the most recent backup, TODAY is the new backup to make. File unchanged in YESTERDAY are hardlnked into TODAY.

The first backup transfers every file, lock stock and barrel. Thereafter backups are incremental due to the hard links. 

Surely this is exactly the same was a local rsync?

**Comment by 357up** [comment]
> Disclaimer: I have not yet tried timeshift, so these are assumptions but I think my theory holds(I would love to hear if it doesn't)
> 
> Couldn't you just mount a sshfs/nfs/smb share and create a single file that you emulate as a drive (https://superuser.com/questions/518554/how-do-you-create-and-partition-a-raw-disk-image) you then simply point timeshift to run backups on the raw diskimage 'dev' location. This would then emulate as a drive that you might be able to point to using timeshift?
> 
> Looking at the 'gui' https://itsfoss.com/backup-restore-linux-timeshift/ timeshift might be looking for 'pure physical disks' based on drivers or other means to differentiate emualte disks so you might need to point to it using the configuration files or some cli commands.
> 
> Then in theory that should work? **But** I have some concerns having it 'remote' as if you f-up your network drivers or something you will ofcourse not be able to simply locally 'timeshift' back. Maybe the raw file can be exported to a drive or some other ways of getting timeshift to create a a 'point in time' that you could export to another file that you then import?
> 
> Like: timeshift get-exact-files-at-date xx-yy-zz --export-to-dummy-file drivestate.raw
> and then simply dd if=drivestate.raw of=/dev/sd{X}
> 
> **However** for most happy penguincampers I think another backup solution is preferred for 'media' and then use timeshift as it's intended purposes. Perhaps try to separate all your media to other drives or(I assume timeshift support lvms or even exclusions of folders) so you back these up using some 'copy-on-write' and validate these are running and then you just timeshift the drive/lv that contains boot and root applications.

This does work (at least with NFS). After the virtual drive in mounted, use `blkid` command to determine UUID of the loop device. Then edit `/etc/timeshift.json` and replace `backup_device_uuid` with the loop device' UUID.

**Comment by tusch001** [comment]
Spending too much time to get timeshift to work with an nfs share I thought I would share my script. It's far from perfect and still needs lots of checks, but maybe it is useful

1. make a backup with timeshift
2. write down UUID and device name of your current timeshift configuration

left to do:

-    check type of snapshot: rsync vs. btrfs - at the moment there is no check so they need to be of the same type
-    check if old timeshift backup device is set before saving uuid for old timeshift device and resetting afterwards
-    after reboot loopback device is gone -> script needs further improvement

```
NFS_MOUNTPOINT='/media/server/backup/timeshift'   # adjust your nfs mount
IMG="${NFS_MOUNTPOINT}/${HOSTNAME}.img"   # name of host serves as image file name
SIZE_GB=25   # image size in GB
BLOCKSIZE=512   # lots of small files so I keep it low
DATE=`date "+%Y-%m-%d"`
COMMENT=$(echo $HOSTNAME-$DATE)   # comment for timeshift snapshot

# ---- variables --- #

# no checks yet
TIMESHIFT_DEV_OLD=$(sudo timeshift --list-devices | grep mounted | cut -d ' ' -f1) && echo old timeshift device = $TIMESHIFT_DEV_OLD
TIMESHIFT_UUID_OLD=`sudo lsblk -o kname,uuid | grep $TIMESHIFT_DEV_OLD | cut -d ' ' -f2` && echo old timeshift uuid = $TIMESHIFT_UUID_OLD
SIZE=$(echo $SIZE_GB*1024*1024*1024 | bc)  # bc = bash calculator
COUNT=$(echo $SIZE/$BLOCKSIZE | bc)   # (max) copies of blocks

sudo cp /etc/timeshift.json /etc/timeshift.json.bak    # backup original timeshift settings

# depending on the size of the partition image this may take some time, it's faster if done manually on the nfs server
dd if=/dev/zero of="$IMG" bs=$BLOCKSIZE count=$COUNT   # make file for partition image
sudo losetup -f "$IMG"   # mount file as loopback device
LOOP_DEV=`sudo losetup -j $IMG | cut -d ':' -f1` && echo loop device = $LOOP_DEV   # save device name in variable
LOOP=`echo $LOOP_DEV | cut -d '/' -f3 ` && echo loop name = $LOOP   # save loop name in variable

printf 'yes\n' | sudo parted "$IMG" mklabel msdos   # create dos partition table without prompt
printf 'o\nn\np\n1\n\n\nw\n' | fdisk "$IMG"   # make one primary partition, full size, write changes without prompt
printf 'y\n' | sudo mke2fs -t ext4 $LOOP_DEV   # format partition without prompt
sudo partprobe -s $LOOP_DEV   # inform kernel about new partition table

UUID=`sudo lsblk -o kname,uuid | grep $LOOP | cut -d ' ' -f2` && echo uuid of loop device = $UUID
sudo timeshift --snapshot-device $UUID   # set timeshift backup device to loop device
# on clients with GUI configure timeshift with the GUI & start backup
# without GUI adjust your settings in sudo nano /etc/timeshift.json and start creating snapshot with
sudo timeshift --create --comment $COMMENT
sudo losetup -d $LOOP_DEV   # unloop

# no checks if old uuid is set 
# sudo timeshift --snapshot-device $TIMESHIFT_UUID_OLD && echo went back to old timeshift backup place with UUID = $TIMESHIFT_UUID_OLD
# better restore old timeshift settings
sudo cp /etc/timeshift.json.bak /etc/timeshift.json

**Comment by x0thrmc-exe** [comment]
I was fiddling with this today, but gave up. There is not enough disk space on my local drive so I can't use timeshift without manually plugging in USB drives. I keep massive NAS drives for storage and backup.

I did not try it, but the next thing I would try would be mounting a network drive, mapping it to /timeshift on the local file system in /etc/fstab . Not sure if it would "trick" TS into putting the backup there or not.

**Comment by solisinvictum** [comment]
I had exact the same Problem. I simply didnt understand why Timeshift didnt allow a destination on a NFS share. And NFS Shares allow everything, what the filesystem allows local. 

Nevermind, i wrote a extension for borg: https://github.com/solisinvictum/borgrestore wich do exact that. 

Is only a little easy script. but it does the job.

**Comment by x0thrmc-exe** [comment]
Now that I actually have timeshift properly set up on a BTRFS partition, I think I understand why this is not needed nor supported. Snapshot are not the same as backups. I use Borg for files backups(on NFS) and timeshift for system snapshot (using BTRFS) and clonezilla for occasional full disk image backups (on NFS) now.

**Comment by solisinvictum** [comment]
That snapshot/backup to a NFS Share isnt supported on BTFS is clear. In this case Timeshift didnt do a lot of work. Because if you use BTRFS you didnt even need Timeshift because take a snapshot and recover a snapshot is only one command on CLI. In This case Timeshift is only a nice GUI for it. 

But in case if you use Timeshift with rsync, that is a whole other Story. There is no Reason why timeshift couldnt use a NFS Share as destination if rsync is choosen. Because NFS (and this is the whole point of nfs and why it was created) can exact everything what is needed.

**Comment by xD0135** [comment]
I agree with the sentiment stated above but I also agree with the author of this project in that this is an open source project and contributions are welcomed :) As a former author of several FOSS I know how difficult it is to find time to dedicate to maintaining a project. Thank you @teejee2008 for the amazing work you have done! :1st_place_medal: 

I have accepted the fact the timeshift has its limitations and perhaps one day someone will provide the aforementioned enhancements, but I still manage to ship a true copy of the snapshots to my NAS via NFS with the added benefit of encryption, all thanks to [duplicity](https://duplicity.gitlab.io/duplicity-web/index.html).

I basically have the following bash script running hourly via cron (starting 5 minutes past the hour) as I have snapshots taken every hour:

```bash
#!/bin/sh

# Timeshift mount
SOURCE="/run/timeshift"
# NFS mount point
REMOTE="file:///home/user/Network/Backup"
# Create a log file for duplicity
LOGFILE="/var/log/duplicity.log"

# Check if lock file exists, if not create it and set trap on exit
if {
    set -C
    2>/dev/null >/var/run/duplicity-backup.lock
}; then
    trap "rm -f /var/run/duplicity-backup.lock" EXIT
else
    printf "\n%s\n" "Lock file exists... exiting" >>"$LOGFILE"
    exit
fi

# Execute backup
duplicity remove-all-but-n-full 3 --force "$REMOTE"
duplicity -v4 \
    --encrypt-key <set your GPG key id> \
    --full-if-older-than 7D \
    --asynchronous-upload \
    --volsize 512 \
    --log-file "$LOGFILE" \
    "$SOURCE" "$REMOTE"

```
Occasionally I manually run the following to verify the integrity of the backup and so far this solution has never failed to produce a corrupt backup (but your mileage may vary):
```bash
$ duplicity verify file:///home/user/Network/Backup /var/run/timeshift
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Sun Nov 28 18:05:01 2021
GnuPG passphrase for decryption: 
Verify complete: 3929530 files compared, 0 differences found.
```
You need to execute the above commands with `sudo` or as `root` to ensure that all files are properly copied during backup and read during the verification or restore process.

My solution isn't perfect by any means but it gets the job done :)

**Comment by ianhundere** [comment]
^ ou, i like that idea. i'm gonna try something similar, but with borgbackup[borgbackuo](https://borgbackup.readthedocs.io/en/stable/) .
