### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Oymate** [teejee2008/timeshift#624]
Spelling synching instead of syncing

**To Reproduce**
1. Click on 'Create'(The icon for creating snapshot)
2. Under creating snapshot it says 'synching'
3. Spelling should be syncing.

**Expected behavior**
It should be 'syncing' instead of 'synching'

**Screenshots**
[Screenshot](https://imgur.com/a/Fq3xxp2)

**System:**
 - Linux Distribution Name and Version: Pop!_OS 20.04 LTS
 - Desktop GNOME
 - Application Version ?

**Comment by j0w0** [comment]
got this too :+1:

**Comment by kreezxil** [comment]
Confirmed in version 20.11.1.r3.g08d0e59-2

![image](https://user-images.githubusercontent.com/3880072/107128382-cf6d0e00-6882-11eb-977b-1bb38b566d51.png)

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.7-3-MANJARO
OS Type: 64-bit
Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
Memory: 23.5 GiB of RAM
Graphics Processor: GeForce GTX 750 Ti/PCIe/SSE2
```

**Comment by j0lol** [comment]
I uh don't think this is actually a spelling mistake https://english.stackexchange.com/questions/681/synced-or-synched

**Comment by kreezxil** [comment]
Well, darn it.

I kept responding, researching for accuracy, deleting, rewriting, rechecking and as much as  I want to be right, I can't be any more than half right.

So, short of a hyperlink to a definition of the word, **yeah no one is going to put that in their program**.  I think that @Oymate or the owner of this program should close this ticket.

IE, @j0lol is correct.

**Comment by Oymate** [comment]
Everyday we wake up, go and fix world problems. And sometimes we find out we are the problem. Sometime we find we are running behind mirages. --~~~~

**Comment by kreezxil** [comment]
That statement doesn't fit. Thinking there is a problem when it's just an
alternate existence of the same thing that turns out to be perfectly
acceptable. I wouldn't call that a mirage. We did unlike our world leaders
come to an amicable understanding and a new level of knowledge.

If it were my app tho, I would change it to the version accepted by the
geeks of the world. After all they're typically the ones who install the
software. The plebs do not, their systems go down in flames and they yell
at their geek who then says "but you were adamant about not wanting a
backup".

It's not my app tho and we did re-establish a somewhat unused vernacular on
the word.

</triggered by a mirage>
