### ISSUE TITLE
Swapfile on Btrfs error: Text file busy / btrfs returned an error: 256 / Failed to create snapshot

### ISSUE THREAD

**Issue by unfa** [teejee2008/timeshift#629]
Hi!

I've recently set up a new Manjaro install on a laptop.

I'm using a swap file on Btrfs (new thing, not tested before) and it seems Timeshift doesn't like that.

This is what I get when I try to create a snapshot with `timeshift --create`:

```
Creating new backup...(BTRFS)
Saving to device: /dev/nvme0n1p4, mounted at path: /run/timeshift/backup
Created directory: /run/timeshift/backup/timeshift-btrfs/snapshots/2020-07-02_16-58-38
E: ERROR: cannot snapshot '/run/timeshift/backup/@': Text file busy

E: btrfs returned an error: 256
E: Failed to create subvolume snapshot: @
Failed to create snapshot
```

What can I do about this?

Obviously I want to exclude the swapfile from my snapshots, but I forgot to do that earlier.

**Comment by ajgringo619** [comment]
I've never been able to get a swapfile to work on BTRFS; tried with multiple versions of Mint & Ubuntu. Can you move it to an EXT4 partition, or make a standalone swap partition?

**Comment by wmutschl** [comment]
I have a guide for a btrfs swapfile which I successfully am able to set up with both Ubuntu and Mint: https://mutschler.eu/linux/install-guides/ubuntu-btrfs/#option-b-swapfile

**Comment by ajgringo619** [comment]
@wmutschl - this looks really cool, especially the grub entries. Does the **timeshift-autosnap-apt** app mimic **apt-btrfs-snapshot**?

As far as the swapfile goes, it seems like too much work; that's why I suggested a dedicated swap partition.

**Comment by wmutschl** [comment]
Yes timeshift-autosnap-apt is a fork of timeshift-autosnap from the AUR for apt based package managers and uses basically the same hook as apt-btrfs-snapshot. However, it runs timeshift to make the snapshots and also has some options to additionally backup your boot partition to have it in the snapshot.

**Comment by emanuc** [comment]
My advice is that if you use swapfile on Btrfs, do it in a subvolume so you don't carry it with you in snapshots.

`# mount -t btrfs /dev/sXY /mnt`
`# btrfs subvolume create /mnt/@swap`
`# chattr -R +C /mnt/@swap`
`# btrfs property set /mnt/@swap compression none` (I don't know if this is actually necessary, because nocow should disable compression)
`# truncate -s 0 /mnt/@swap/swapfile`
`# fallocate -l 512M /mnt/@swap/swapfile` (The size is up to you)
`# chmod 600 /mnt/@swap/swapfile`
`# mkswap /mnt/@swap/swapfile`
(Now just add it to /etc/fstab)
(mount subvolume)
`UUID /swap btrfs defaults,subvol=@swap`
(mount Activate the swap file)
`/swap/swapfile none swap defaults 0 0`

**Comment by geekpete** [comment]
Relocating the swapfile into it's own dedicated subvolume worked quite well.
I've submitted doc PR https://github.com/teejee2008/timeshift/pull/754 to document the error that occurs for users that hit it and to advise against this pattern generally with the alternative.
