### ISSUE TITLE
Is timeshift still maintained?

### ISSUE THREAD

**Issue by doogie544** [teejee2008/timeshift#648]
According the the Arch wiki Timeshift is no longer maintained.  They site this post: https://github.com/teejee2008/timeshift/issues/145#issuecomment-628658962

The comment by Tony was posted very shortly after Timeshifts last update.  I understand that Timeshift is not the kind of program that need frequent updates as it is not adding new features and only needs updated to keep up with changes or for bug fixes.  I'm also aware that Tony is not the only contributor to the project.  That leads me to my question.

Has Timeshift been effectively abandoned or did the editor of the Arch wiki take a comment and make too much out of it?  I'm hoping that it is the latter, Timeshift is just about the best backup for `/` that I know of.

As an aside, if the project has been abandoned, is there a reliable alternative out there that has the same function and ease-of-use?

**Comment by teejee2008** [comment]
This app is not abandoned but it not as actively maintained as people would like. I currently update this app once a year.

There are other developers from Linux Mint who have contributed code changes. The code contributions from Linux Mint team was during the time when it was integrated into Linux Mint (end of 2018). Linux Mint maintains a fork of the code where they make changes that are specific to the distribution (better integration with Mint apps, etc). Even if I were to stop updating the app in future, the Linux Mint team is more than capable of picking up the development.

As you noted, this is not the kind of app that requires frequent changes. However, there are open issues and feature requests that can be worked on.

I rarely face a system issue that is serious enough to restore the system to a previous date. And on the rare occasion that I need to restore my system this app works fine for me (I only use BTRFS snapshots). Hence I don't have the interest to continue making changes to the app.

When people complain that this app is unmaintained what they mean is the lack of support. If people ask a question or report an issue on this issue tracker they will not receive a response for months. This is not something that can be helped. This is a free app and there are thousands of users. It is not possible for one developer to provide support to users in their free time. Even if I had the time, I have no interest in providing support. I have other things I like to do with my free time on weekends.

If someone needs support for this app they should post it on the Linux Mint forums so that other users in the community can help them out. Users on the Linux Mint forums are active and helpful and you will get the support you need.

If someone needs new features in the app they must be willing to do the work rather than wait for someone to do it for them. The whole point of open-source development is that people can download the source code and modify it according to their requirements. Open-source doesn't mean free labour, it means free code. If someone needs changes then they should download the source code, make the changes, test it properly and then submit a pull request. The changes will be reviewed and merged in the next update.

**Comment by wmutschl** [comment]
Maybe you could put this information also in the Readme of the repository, so the community is aware of where to raise issues and how to get help?

**Comment by teejee2008** [comment]
Done

**Comment by teejee2008** [comment]
This information was already there in issue templates. When someone adds an item to the Issue Tracker they will see this message.

**Comment by philmmanjaro** [comment]
Updating it just once a year is odd to me. There are more than 303 open issues on this tracker. Why that release schedule?

**Comment by teejee2008** [comment]
That's all the time that I can spare.

For example, I responded to this question today. I have already spent more than an hour on a weekday responding to this topic.

**Comment by teejee2008** [comment]
Multiply an hour by 303 and multiply again for the apps that I maintain. You do realise that I do this for a hobby right? I have a full time job that takes up most of my day. Weekend are all that I can spare. And I would rather spend my weekends on something that I enjoy rather than something that feels like work.

**Comment by mwoz123** [comment]
@teejee2008 - Tony thanks for great app, and all time you spend on developing and maintaining Timeshift - really appreciate it :)

I know you don't have much time and you do it without any charge.

As last merged PR is >5 months old, I was wondering if this project could have at least 1 more maintainer that:
could review, request changes & accept incoming PRs
[you could make a "maintainer request" - don't worry - it won't be me as I've no experience in Vala ;) ], 
so this app could be active in development again?

or maybe create a form of sponsorship - other opensource project also benefit from sponsors e.g. : 
https://github.com/keeweb/keeweb
https://github.com/hovancik/stretchly
?
Those are the first opensource apps that I'd in mind - not very popular but have some income.

Or maybe do both?

I think this app is too great to be frozen in development..

ps: in person I wanted to learn some basics of Vala to create simple PR but from PR list it looks as-if the project is dead, so it scared me away:(

**Comment by easthvan** [comment]
> Multiply an hour by 303 and multiply again for the apps that I maintain. You do realise that I do this for a hobby right? I have a full time job that takes up most of my day. Weekend are all that I can spare. And I would rather spend my weekends on something that I enjoy rather than something that feels like work.

Hello :-)

I am a 3 days old Linux noob and have been trying to setup your freely provided Timeshift app for hours, based on many Youtube and Wiki recommendations as so many users love it including pros. Just so you know, I was willing to make a tiny donation payment after I setup and can sucessfuly use, revert a backup etc. So some of us are willing to pay for the value. I would recommend to place a colored DONATE button on the main screen of the app which opens your Paypal payment site directly. I am a 4x year old sales guy who has zero Linux knowledge that right. 

The app is not recognizing my Btrfs volume on this encrypted setup. I will post my question at Manjaro etc forum of course, so no pressure.

![image](https://user-images.githubusercontent.com/71530894/94083201-f6123700-fe02-11ea-9036-35da0c53caff.png)

**Comment by floatingrain** [comment]
I just forked this project and merged most open prs from this repo, but I don't know how to build it, and it depends so many packages. If there's a guide book, it will be nice.

**Comment by lvbaal** [comment]
> > Multiply an hour by 303 and multiply again for the apps that I maintain. You do realize that I do this for a hobby right? I have a full time job that takes up most of my day. Weekend are all that I can spare. And I would rather spend my weekends on something that I enjoy rather than something that feels like work.
> 
> Hello :-)
> 
> I am a 3 days old Linux noob and have been trying to setup your freely provided Timeshift app for hours, based on many YouTube and Wiki recommendations as so many users love it including pros. **Just so you know, I was willing to make a tiny donation payment after I setup and can successfully use**, revert a backup etc. So some of us are willing to pay for the value.
> I guess, unfortunately most users do not honor the work, the freeware app even if they can afford it and use it.
> 
> BTRFS: The app is not recognizing my Btrfs volume on this encrypted setup. I will post my question at Manjaro etc forum of course, so no pressure.
> 
> ![image](https://user-images.githubusercontent.com/71530894/94083201-f6123700-fe02-11ea-9036-35da0c53caff.png)
> 
> RSYNC: Works for me I think:
> 
> ![image](https://user-images.githubusercontent.com/71530894/94083771-48078c80-fe04-11ea-816f-ae048300bae7.png)

Hello, I read your remark about setting up TimeShift on your Manjaro Linux system. I don't know how far you got with this, but I would like to make the suggestion to you to look at Garuda Linux with Grub integrated TimeShift support on BTSFS. I have made the switch to this distro and it's really re-assuring to be ale to go back to an earlier state of the system when in trouble.
