### ISSUE TITLE
Timeshift should unmount target device after having finished snapshot

### ISSUE THREAD

**Issue by oldtomdevel** [teejee2008/timeshift#653]
Issue refers to Timeshift v20.03 in Linux Mint 20 Cinnamon 64bit

Timeshift mounts the target device for the snapshots at the mounting point `/run/timeshift/backup`.
Unfortunately, the target device is not unmounted after having finished the snapshot or after the GUI is closed.
The mounting stays active till shutdown.
But this causes an annoying effect, as described below, if the target device is also used for user data.

My configuration is as follows:
* standard Mint installation on a small SSD
* another big SSD as my personal drive which is permanently mounted by `fstab` at some mounting point and used for my personal data (that data is referenced by some softlinks in my `/home` folder)
* Timeshift is activated and saves its snapshots on the big SSD i.e. the one which is also permanently mounted as personal data storage.

The usage of one device as target device for Timeshift's snapshots and as storage for user data as well, is an allowed configuration.

When Timeshift was running i.e. when the target device has been mounted by Timeshift, any file on the big SSD can be achieved by two different paths, namely as `/run/timeshift/backup/[subpath to file]` and as `[permanent mounting point]/[subpath to file]`. If you now delete such a file i.e. move it to trash, it appears twice in the trash, namely with both paths. From a user's point of view this is not the expected behaviour. Any file deleted by the user should should appear only once. The double entry is caused by the additional mounting executed by Timeshift.

Therefore, Timeshift should unmount the target device when the mounting is not needed any more.

**Comment by Golddouble** [comment]
I also would suggest to unmount the target device when timeshift is closed because of this:
https://github.com/teejee2008/timeshift/issues/675

**Comment by Natetronn** [comment]
Timeshift v20.11.1
Manjaro KDE 20.2

I'm running into this as well and see two mount points in `/etc/mtab` for the same drive `/dev/sdd1`

```
/dev/sdd1 /wdusb ext4 rw,relatime,discard 0 0
/dev/sdd1 /run/timeshift/backup ext4 rw,relatime,discard 0 0
```

Using Dolphin File Manager, the path is `/run/timeshift/backup/`instead of `/wbusb`.

Note: `/dev/sdd1` is an External USB.

Possible duplicate: https://github.com/teejee2008/timeshift/issues/578#issuecomment-724350482

**Comment by GregTheHun** [comment]
I'm also seeing this same issue in Manjaro xfce.

The way I have my settings in Timeshift right now:

![Screenshot_2021-02-24_12-31-15](https://user-images.githubusercontent.com/19254816/109048469-b8108c00-769c-11eb-9d14-86a97713998a.png)
![Screenshot_2021-02-24_12-31-41](https://user-images.githubusercontent.com/19254816/109048474-ba72e600-769c-11eb-91f2-a78fcc8bf393.png)
![Screenshot_2021-02-24_12-32-06](https://user-images.githubusercontent.com/19254816/109048483-bc3ca980-769c-11eb-8b42-08568f00bdf0.png)
![Screenshot_2021-02-24_12-32-26](https://user-images.githubusercontent.com/19254816/109048491-be066d00-769c-11eb-988a-2ef2a08ee38b.png)

**Comment by moonraker2** [comment]
Same issue in Xubuntu 20 (Timeshift not unmounting backup disk from /run/timeshift/ after backup has completed):

![image](https://user-images.githubusercontent.com/30633152/109541113-b5aa9980-7ac3-11eb-8f74-fbc2533ffba7.png)

**Comment by nostromo123** [comment]
Same issue here with DEBIAN Bullseye and timeshift 20.11.1-1

![Bildschirmfoto_2021-08-22_11-28-52](https://user-images.githubusercontent.com/17964433/130350055-4a838fe3-65f8-418f-9372-4e7dbcb9f614.png)

**Comment by odonnellmj** [comment]
I am having the same problem on a brand new install of Ubuntu 21.10. I have large USB attached external disks which I use for several backups, one with Timeshare and others with my own rsync scripts. I like to automount on /media/<username>/<unique disk ID>. Timeshare does its own second mount.

Besides the problems described above, since Timeshift automounts /dev/sdb1, presumably without checking the disk ID, I may be stuck having Timeshift mount other USB devices. I haven't yet checked whether this happens.
