### ISSUE TITLE
Timeshift doesn't umount drive as root when exit (GDBus.Error Device or resource busy)

### ISSUE THREAD

**Issue by Tanatole** [teejee2008/timeshift#689]
**Describe the bug**
When I launch Timeshift, it obviously mount my backup drive as root. Here is my mount output:
```/dev/mapper/luks-1afc320c-xxxxx-xxx7-xxxx3-xxxxx600c on /run/timeshift/backup type ext4 (rw,relatime,stripe=8191)```
**The bug** is when closing Timeshift, this drive **is not unmounted**.
And so, when you want to "eject" your drive as "standard user". You get this GDBus error:
```GDBus.Error:org.freedesktop.UDisks2.Error.Failed:Error locking /dev/dm-3 (/-dev/sdb): Failed to deactivate device: Device or resource busy.```

**To Reproduce**
1. Launch Timeshift.
2. Enter root password.
3. Make sure you have an external drive to be mounted by timeshift as root.
4. Exit Timeshift.

**Expected behavior**
Timeshift should unmount this drive because it mounted it itself.

**System:**
 - Linux Mint 20 Ulyana
 - Desktop: Xfce 4.14.2
 - Timeshift version: 20.03.2+ulyana

**Hard drive used to backup:**
Toshiba 500GB with LUKS Encryption (version 1)
(I unlock it before launching Timeshift.)

**Workaround:**
As root or sudo, enter:
```# umount /run/timeshift/backup```

**Comment by Golddouble** [comment]
I also have already reported this, because this also bothers me:
https://github.com/teejee2008/timeshift/issues/675

**Comment by OmarShawky1** [comment]
it happens to all devices but it isn't a bug after all; you can easily unmount it.

**Comment by Natetronn** [comment]
> it happens to all devices but it isn't a bug after all; you can easily unmount it.

I mean, sure, I guess. But who wants to unmount what Timeshift should do on its own every time? Having to unmount several times a day, everyday, seems like something a computer is good for, no?

**Comment by Tanatole** [comment]
> it happens to all devices but it isn't a bug after all; you can easily unmount it.

Come on ! It's hardly not a bug.
You can't ask a "normal" user to log as root and unmount /run/timeshift/backup
It's not serious !

And even for advanced users, it's really annoying.

The algo is quite simple : When timeshift mount the drive, it sets a flag "I mounted the drive myself", and when the job is done, if the flag is set, umount /run/timeshift/backup.

Seriously, this is not a detail. I want my clients and friends to use timeshift, but it's a huge shame if they have to open a terminal at the end of every backup !!!

So please, take an hour on this one :-)

**Comment by NANDLAB** [comment]
I agree to the other participants.

I use timeshift for system backups on Linux Mint and it generally works pretty well.

But the behavior, that timeshift does not unmount the target device at the end, is really annoying.

I use an external usb hard drive for backups. I plug it in, run timeshift and when it finishes, I would like to safely remove the drive. But when I click safely remove in the file manager, it errors because `/dev/sdb1` is still mounted to `/run/timeshift/backup`.

So I have to open the terminal and manually type:
`sudo umount /dev/sdb1 && sudo disksctl power-off -b /dev/sdb`
Only then I can detach the usb cable.

This is definitely not the expected usage for the end user!!

I would really appreciate, if the target device is either
- unmounted automatically if you close the timeshift window
- or there is a button to unmount (and maybe also mount) it manually

Please add this essential functionality :)

**Comment by Golddouble** [comment]
I use timeshift the same way like @NANDLAB.

**Comment by Moonbase59** [comment]
Same here on Linux Mint 20.3. Took me a mo to realize Timeshift mounting but not unmounting an external drive. Clearly something _I_ can handle but _not_ the many friends I recommended Timeshift to!
