### ISSUE TITLE
Use one external disk for several computers to be "TimeShifted" : OK ?

### ISSUE THREAD

**Issue by jmg-74** [teejee2008/timeshift#699]
**Bug ?**
I don't know if it is a bug or not : I store my TimeShift "backups" on **one external disk, for two different computers**. It seems to work but **I'm afraid there could be a mix between the two backup** (because of the incremental approach). Does TimesShift keep a separate trace of each install ? 
If not, I'll create and use two separate partitions, but it could be useful to explain this in the doc. And/or to allow using a different directory than "timeshift" (e.g. one for each computer. I've noticed it is already possible to tag each backup and I've done it to avoid confusions).

**System:**
(On both computers)
 - Mint 20 (one was initially on Mint 19.3)
 - Cinnamon
 - TimeShift 1.15 (from apt install)
 - USB external disk with one ext4 partition to store "backups".
 - Default params: RSINC mode, personal data excluded. Manual backup only (not croned)

Thank you so much for this great tool and for taking the time to read this question !

**Comment by jmg-74** [comment]
Seems to be confirmed: [https://forums.linuxmint.com/viewtopic.php?f=47&t=275688](https://forums.linuxmint.com/viewtopic.php?f=47&t=275688) 
Please consider that Mint is designed for beginers and then not necessary aware of how exactly TimeShift works, so it could be useful to mention it in the doc.

**Comment by teejee2008** [comment]
It can be done but it is not recommended. Snapshots for both systems will be saved together. This is very inefficient and each snapshot will take up more space (since each snapshot is linked from previous one and previous one may be from a different system).

Use separate partitions for each system.

**Comment by jmg-74** [comment]
OK, thank you for taking the time to answer.

**Comment by MAlfare** [comment]
teejee2008:
It can be done but it is not recommended. Snapshots for both systems will be saved together. This is very inefficient and each snapshot will take up more space (since each snapshot is linked from previous one and previous one may be from a different system).

I think, you are wrong here.
In this thread, a guy tried it out, and it worked.
The log shows, that the correct predecessor was referenced in rsync options for a new snapshot, which was not a complete copy.
I think using the  UUID from the info.jason makes this happen.
https://forums.linuxmint.com/viewtopic.php?f=90&t=360279](https://forums.linuxmint.com/viewtopic.php?f=90&t=360279) 
Perhaps TS is more intelligent than generally assumed?

Maybe I am in error.
A clear statement why it works or why it cannot work would be very appreciated
