### ISSUE TITLE
timeshift with btrfs on fedora 34 fails to backup my kernal and device drivers.

### ISSUE THREAD

**Issue by kheshav-coder** [teejee2008/timeshift#762]
i am using fedora 34. I've installed timeshift and configured my system for btrfs support according to this source [https://mutschler.eu/linux/install-guides/fedora-btrfs/#create-btrfs-subvolumes--and-home](url) timeshift seems to take snapshots without any error, but when I restore a snapshot, the system loses all my device drivers (wifi adapter not recognized) and most importantly the kernel remains to be the newer one and not restored to the old version which was there when I took the snapshot. I am not sleeping due to this problem. if anyone can tell me what could possibly be wrong, I'll be really thankful.

**Comment by ShrirajHegde** [comment]
It is because Fedora uses a separate boot partition formatted as ext4.

You can set up some script to periodically backup the boot partition (should be less than a GiB after compression) and restore the nearest boot partition image.

Or you can move boot partition contents into root partition with BTRFS (grub supports BTRFS read-only) and then update grub config.

**Comment by ShrirajHegde** [comment]
feature-request #764 would eliminate all these issues
