### ISSUE TITLE
Timeshift not unmounting destination after snapshot complete

### ISSUE THREAD

**Issue by Andy2051** [teejee2008/timeshift#809]
Even if the destination partition is already mounted, timeshift insists on mounting it again at `/run/timeshift/backup`. The problem is that when the snapshot has completed timeshift does not unmount `/run/timeshift/backup`. This can cause problems elsewhere in the system.

More details here:
[https://forums.linuxmint.com/viewtopic.php?p=2076784#p2076784](url)
[https://forums.linuxmint.com/viewtopic.php?f=47&t=346310&p=1995402&hilit=timeshift#p1995402](url)
EDIT - clicking on the links doesn't work, but copy/paste into your browser does?

I have my snapshot partition mounted via fstab at `/media/ultrabay`. It shows up in the output from `df`. If I check the mountpoint with  `lsblk -nio mountpoint /dev/sdc2` it shows up as `/run/timeshift/backup`. If I then unmount `/media/ultrabay` via nemo (running LM20.2 cinnamon) it doesn't show up in `df` and rerunning `lsblk` shows that `/run/timeshift/backup` has also been unmounted.

At the time I did the above it was at least five hours since the snapshot was taken and completed, sdc2 was still mounted at `/run/timeshift/backup`.

**Comment by NANDLAB** [comment]
I have the same problem.

I use timeshift for system backups on Linux Mint and it generally works pretty well.

But the behavior, that timeshift does not unmount the target device at the end, is really annoying.

I use an external usb hard drive for backups. I plug it in, run timeshift and when it finishes, I would like to safely remove the drive. But when I click safely remove in the file manager, it errors because `/dev/sdb1` is still mounted to `/run/timeshift/backup`.

So I have to open the terminal and manually type:
`sudo umount /dev/sdb1 && sudo disksctl power-off -b /dev/sdb`
Only then I can detach the usb cable.

This is definitely not the expected usage for the end user!!

I would really appreciate, if the target device is either
- unmounted automatically if you close the timeshift window
- or there is a button to unmount (and maybe also mount) it manually

Please add this essential functionality :)

**Comment by FlailAway** [comment]
>     * unmounted automatically if you close the timeshift window

Why not run Timeshift in a BASH script that unmounts on successful completion of the backup.?

**Comment by Andy2051** [comment]
Yes you could run a bash script, but I have timeshift setup to automatically take a snapshot every day. I'd have to develop the script to run either as a cron or anacron job and this is functionality that is built into timeshift, it should work properly. I develop linux backup software (foxclone) and my premise is that you must leave the system in the same state you found it. So if you need to mount partitions, whenever you have done what you want, you need to unmount them. This is what foxclone does, if a partition is already mounted, it uses the mountpoint; if not it mounts it. When it is finished, if it had to mount the partition, it unmounts it. If it was already mounted, it makes sure that it is still mounted at the original mountpoint.

While I can sort of see why timeshift insists on mounting the destination, it is not difficult to check to see if the destination is already mounted and if so, then use the existing mountpoint. If timeshift wants to mount the destination separately in a different location then it SHOULD unmount it when finished.

**Comment by CoRoe** [comment]
I also think that this should be fixed.

**Comment by cebas** [comment]
I'm also annoyed by this behaviour. Please, fix it.

**Comment by gimplyworxs** [comment]
Same here.
It's not only that Timeshift mounts for writing the backups. And doen't unmount.
It also mounts for its hourly check if a backup is to be written.And leaves it mounted!
Really annoying. Please fix.

**Comment by Robin-Sch** [comment]
I lost my whole system. I thought it was a config dir/left over files due to `backup` being in there (removed backups > uninstalled timeshift > found that dir and rm -rf)

**Comment by Andy2051** [comment]
Thank you.

**Comment by cebas** [comment]
Tested with a manual run and working fine. Thanks!
