### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by NikoKrause** [teejee2008/timeshift#93]
Take out the `Refresh list` from the menu and add it as a button in timeshift:
![timeshift-4](https://user-images.githubusercontent.com/8415124/33788614-95ac9332-dc73-11e7-8712-9cb57dbd7f4d.png)

**Comment by teejee2008** [comment]
Refreshing the list is not necessary which is why it is hidden in the drop-down menu. Any actions (create, delete, etc) executed from UI will refresh the list automatically. 
It's needed only when the GUI is kept open for a long time and a scheduled snapshot was created in the background while the UI was open.
Adding it to the toolbar may give users the idea that they need to keep refreshing the list.
